### ISSUE TITLE
Tab focus is lost when using keyboard to navigate

### ISSUE THREAD

**Issue by ianb** [peterdotjs/atom-synced-sidebar#1]
When I change tabs, e.g., using Cmd-[ and Cmd-], each time I change tabs (and this package does its scrolling) the focus seems to go to the sidebar, and so the keyboard shortcuts stop working until I click back on the tabs.

**Comment by peterdotjs** [comment]
@ianb, thanks for filing. Looking into it.

**Comment by peterdotjs** [comment]
Fixed in commit 7f3660c9dd2e856c2406cc48c523a25d00d598a3.

@ianb fix is available in version 0.2.3

**Comment by vip9** [comment]
When using https://atom.io/packages/tab-history (Tab History overrides the default 'pane:prev-item' and 'pane:next-item) I can still reproduce this behaviour. Ctrl+tab switches tabs and after sync the focus is on the sidebar.
